# Generated by Django 6.1 on 2026-09-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='order_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Hotel', 'Hotel')], default='Standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='hoteltab',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('room_number',), name='unique_active_room'),
        ),
    ]
